export const NAMES = [
    'Aerg-Tval',
    'Theras',
    'Agn',
    'Therg',
    'Schlefzum',
    'Torvul',
    'Belsum',
    'Törn',
    'Domn',
    'Urm',
    'Vükkan',
    'Drugel',
    'Börda',
    'Vagal',
    'Daeru',
    'Vatan',
    'Kathan',
    'Von',
    'Felban',
    'Vrakh',
    'Gotven',
    'Vresi',
    'Senkil',
    'Wemut',
    'Grin',
    'Skelh',
    'Grittr',
    'Burder',
    'Haerü',
    'Jaurk',
    'Hargha',
    'Thron',
    'Harmug',
    'Tarvl',
    'Jotna',
    'Yvtuk',
    'Karg',
    'Urkin',
    'Karva',
    'Gretil',
    'Katla',
    'Lirk',
    'Keftar',
    'Galt',
    'Klort',
    'Oren',
    'Kratar',
    'Morgar',
    'Kutz',
    'Fegan',
    'Kvetin',
    'Wakta',
    'Lygan',
    'Sunn',
    'Margar',
    'Gaust',
    'Merkari',
    'Gravuld',
    'Nagl',
    'Krangel',
    'Niduk',
    'Gneth',
    'Nifehl',
    'Kluvrist',
    'Prügl',
    'Qift-Mol',
    'Qillnach',
    'Mardul',
    'Risten',
    'Klovan',
    'Svind',
    'Dölun'
];

export const TRAIT = [
    'an annoyed',
    'a sick',
    'a nervous',
    'a bleeding',
    'an aggresive',
    'a limping',
    'a confused',
    'a blind',
    'a scared',
    'a scarred',
    'a deaf',
    'an envious',
    'a rotting',
    'a sad',
    'an itching',
    'a desperate',
    'a stinking',
    'a pompous',
    'a dying',
    'a bitter',
    'a starving',
    'a gullible',
    'a pained',
    'a lazy',
    'a wounded',
    'a naïve',
    'an exhausted',
    'a gaudy',
    'a heretical',
    'a worried',
    'a hopeless',
    'an apathetic',
    'a drunk',
    'a gaunt',
    'a betrayed',
    'a thieving',
];

export const TRADE = [
    'baker',
    'butcher',
    'gravedigger',
    'peddler',
    'drifter',
    'soothsayer',
    'snake breeder',
    'blacksmith',
    'executioner',
    'innkeeper',
    'peasant',
    'icon painter',
    'brigand',
    'thief',
    'deserter',
    'herbalist',
    'lawless scum',
    'former hermit',
    'priest',
    'priestess',
    'drudge',
    'dreg',
    'struggling artisan',
    'monkey tamer',
    'bell ringer',
    'shitshoveller',
    'ditch digger',
    'rat-catcher',
    'mercenary',
    'witch hunter',
    'jailer',
    'torturer',
    'bookbinder',
    'bookburner',
    'tax collector',
    'full-time gambler',
    'seafarer',
    'corpse collector',
    'barber-surgeon',
    'miner',
    'bomb chemist',
    'vagabond',
    'hunter',
    'cruel captain',
    'corrupt clerk'
];

export const CONCERN = [
    'incredible debt',
    'stolen goods',
    'run-in with a gang of ruffians',
    'kidnapped kin',
    'possessed spouse',
    'family curse',
    'murdered friend',
    'weird wart',
    'run-in with the local corrupt priests',
    'anxiety over the end of the world',
    'muffled prisoner',
    'pool of blood spreading outward'
];

export const WANTS = [
    'to travel',
    'a glorious death',
    'bloodshed',
    'forgiveness',
    'revenge',
    'treasure',
    'to retire',
    'love',
    'a drink',
    'to be left alone',
    'knowledge',
    'to feel that there is some kind of meaning or purpose to it all'
];

export const APOCALYPSE = [
    'It\'s best to accept it. Nothing anyone can do about it.',
    'Someone else will fix it. Not my fucking problem.',
    'About damn time! This place should have burned ages ago...',
    'We\'re doomed! We\'re just playthings made to suffer!'
];

export const ISREALLY = [
    'a spy',
    'an inquistor',
    'undead',
    'reborn',
    'a necromancer',
    'dying of the plague',
    'an assassin',
    'a shapeshifter',
    'desperate for money',
    'filthy rich',
    'full of insects',
    'a cannibal',
    'a serial killer',
    'possessed by a daemon',
    'a daemon',
    'cursed',
    'a cultist',
    'the head of a murder cult',
    'a disguised noble',
    'just a mirage'
];

export const SPECIES = [
    'Earthbound',
    'Wild Wickhead',
    'Pale One',
    'Basalisk-born',
    'Gnoll',
    'Human',
    'Skeleton',
    'Giant',
    'Half-Giant',
    'Bisontaur',
    'Ghoul',
];

export const FUR = [
    'greasy black',
    'blood red',
    'gravedirt brown',
    'bile yellow',
    'bone white',
];

export const SCALES = [
    'void black',
    'blood red',
    'rust orange',
    'bile yellow',
    'bruise blue',
    'rotting green',
    'unfathomably violet'
];

export const MAIN_PRONOUN = [
    'He',
    'She',
    'They'
];

export const SECONDARY_PRONOUN = [
    'Him',
    'Her',
    'Them'
];

export const SKIN_TONE = [
    'ashen',
    'leathery tanned',
    'onxy',
    'ruddy',
    'clay',
    'driftwood'
];

export const BUILD = [
    'stout',
    'gaunt',
    'rotund',
    'muscular',
    'curvacious',
    'starved',
];

export const WHATTHEYVALUE = [
    'fireplace discussions',
    'praise',
    'endless tasks',
    'items as payment',
    'carnal relations',
    'diluted black poison',
    'the chance to hold long monologues about themself',
    'verbal conflicts within the group',
    'getting paid in sharp weapons',
    'burnt meat',
    'depressing stories',
    'captured slaves',
    'not having to use their speciality all the time',
    'cleanliness',
    'melancholic melodies to listen to',
    'a couple hours alone in darkness',
    'wine',
    'obscure rituals with the group',
    'payment in silver',
    'food',
    'gossip',
    'liquor',
    'pointless death',
    'credit for exploits'
];

export const SPECIALITY = [
    'can disarm traps at DR8 (you need to find them first)',
    'can steal a single item at DR8',
    'can climb impossible routes alone at DR8',
    'can find trails and corners that keep the group hidden at DR8',
    'can create d2 doses of a random decoction (see the class Occult Herbmaster), once per day',
    'can create d2 doses of Elixir Vitalis (heals d6 HP and stops infection), once per day',
    'can use one random unclean Power, once per day',
    'can use one random sacred Power, once per day',
    'can serve as a walking lightsource',
    'can wield a knife like no other (d4+2)',
    'can perform a backstab (test DR8 with d20 rolled by GM. Deals weapon damage +3)',
    'can cook an excellent meal (recover an extra d4 HP when resting)',
    'can find the right path',
    'can sense danger',
    'can make/repair items'
];