export const NAMES = [
    'Whitney',
    'Erika',
    'Lance',
    'Ripley',
    'Coheed',
    'Cambria',
    'Vaxis',
    'Newo',
    'Orthis',
    'Adrian',
    'Rem',
    'Aranaia',
    'Lem',
    'Breem',
    'Vimes',
    'Skint',
    'Saffron',
    'Beryl',
    'Imogen',
    'Jar',
    'Silva',
    'Horst',
    'Haxar',
    'Striga',
    'Edelhart',
    'Gavlan',
    'Thorn',
    'Liv',
    'Raphiela',
    'Kreet',
    'Leander',
    'Mercutio',
    'Satis',
    'Elizabeth',
    'Grim',
    'Eldread',
    'Odham',
    'Willow',
    'Seasong',
    'Avalanche',
    'Judas',
    'Cassius',
    'Albert',
    'Rani',
    'Agrippa',
    'Streben',
    'Imnel',
    'Doc',
    'Norman',
    'Aliaster',
    'Adalina',
    'Sabrina',
    'Sperro',
    'Eugene',
    'Vincent',
    'Viktor',
    'Rhonda',
    'Jenny',
    'Regin',
    'Dearni',
    'Kotlin',
    'Gram',
    'Din',
    'Tyrant Slayer',
    'Obadiah',
    'El',
    'Moil',
    'Theo',
    'Marrianne',
    'Rom',
    'Louis Rex',
    'Varius',
    'Altum',
    'Ephie',
    'Anya',
    'Ramal',
    'Cirrus',
    'Foam',
    'Shale',
    'Bismark',
    'Prismarine',
    'Crush',
    'Abyss',
    'Jacklyn',
    'Zant',
    'Camilla',
    'Vilgot',
    'Ellis',
    'Falak',
    'Marshall',
    'Faragar',
    'Pelle',
    'Gaur',
    'Dutch',
    'Jaspar',
    'Sined',
    'Karsus',
    'Albedo',
    'Astarot',
    'Zola',
    'Kaiman',
    'Noi',
    'Shin',
    'Sybil',
    'Errol',
    'Iris',
    'Pyrite',
    'Rorick',
    'Hitomi',
    'Gianna',
    'Vigil',
    'Purity',
    'Pitch',
    'Bagherra',
    'Cersei',
    'Quinn',
    'Ein',
    'Luna',
    'Lemillion',
    'Matrakin',
    'Zandakar',
    'Leviathan',
    'Mary',
    'Amon',
    'Abraxas',
    'Adrammelech',
    'Akuma',
    'Baal',
    'Barbatos',
    'Asmodeus',
    'Astaroth',
    'Belial',
    'Clauneck',
    'Eligos',
    'Flauros',
    'Focalor',
    'Foras',
    'Forneus',
    'Furcas',
    'Furfur',
    'Gaap',
    'Gamigin',
    'Gemory',
    'Haagenti',
    'Halphas',
    'Ipos',
    'Kimaris',
    'Leraje',
    'Malphas',
    'Marbas',
    'Marchosias',
    'Morax',
    'Naberius',
    'Orias',
    'Orobas',
    'Ose',
    'Paimon',
    'Phenex',
    'Raum',
    'Ronove',
    'Sabnock',
    'Sallos',
    'Seere',
    'Shax',
    'Sitri',
    'Stolas',
    'Surgat',
    'Valac',
    'Valefar',
    'Vassago',
    'Vine',
    'Zagan',
    'Zepar',
    'Ziminiar',
];

export const TRAIT = [
    'an aggrivated',
    'a plague-ridden',
    'a skittish',
    'a bleeding',
    'an belligerent',
    'a limping',
    'a bewildered',
    'a blind',
    'a terrified',
    'a scarred',
    'a deaf',
    'a covetous',
    'a rotting',
    'a melancholic',
    'an itching',
    'a forlorn',
    'a foul-smelling',
    'an imperious',
    'a dying',
    'an indignant',
    'a ravenous',
    'an exploitable',
    'a wounded',
    'a shiftless',
    'a naïve',
    'an exhausted',
    'a garish',
    'an iconoclastic',
    'a troubled',
    'a wretched',
    'an apathetic',
    'a drunk',
    'a gaunt',
    'a betrayed',
    'a thieving',
];

export const TRADE = [
    'baker',
    'butcher',
    'gravedigger',
    'peddler',
    'drifter',
    'soothsayer',
    'eel breeder',
    'blacksmith',
    'executioner',
    'innkeeper',
    'peasant',
    'holy symbol illustrator',
    'highwayman',
    'thief',
    'deserter',
    'alchemist',
    'lawless scum',
    'former hermit',
    'priest',
    'priestess',
    'menial laborer',
    'worthless waste of space',
    'struggling artist',
    'hound tamer',
    'bell ringer',
    'shitshoveller',
    'ditch digger',
    'rat-catcher',
    'mercenary',
    'witch burner',
    'gaoler',
    'torturer',
    'bookbinder',
    'bookburner',
    'tax collector',
    'full-time knucklebones player',
    'sailor',
    'corpse collector',
    'barber-surgeon',
    'miner',
    'bomb maker',
    'vagabond',
    'hunter',
    'merciless master',
    'amoral administrator',
    'lamplighter'
];

export const CONCERN = [
    'insurmountable debt',
    'treasures that were recently stolen',
    'run-in with a gang of thugs and lowlives',
    'missing family',
    'daemon-infested spouse',
    'cursed family',
    'murdered friend',
    'odd growth',
    'run-in with the local maligned missionaries',
    'anxiety over the end of the world',
    'prisoner, bound, gagged, and struggling',
    'boots filled with blood'
];

export const WANTS = [
    'to leave this shithole',
    'to die in a legendary manner',
    'to kill. Doesn\'t matter what',
    'to be forgiven for the unforgivable',
    'revenge',
    'piles of glittering gold and sparkling gems',
    'to finally settle down',
    'to find someone to love',
    'booze so powerful that it makes one forget their sins',
    'to be alone with ones thoughts',
    'the secrets of this cold and fucked up place',
    'to finally feel something, anything'
];

export const APOCALYPSE = [
    'Nothing anyone can do about it.',
    'Not my fucking problem.',
    'This place should have burned ages ago!',
    'We\'re doomed! We\'re just playthings made to suffer!'
];

export const ISREALLY = [
    'a spook',
    'an inquistor',
    'a rotting corpse pretending to live',
    'newly reincarnated',
    'a necromancer',
    'riddled with sickness and bile',
    'an assassin',
    'a shapeshifter',
    'desperate for money',
    'overflowing with riches',
    'a hollow shell, filled with crawling bugs',
    'a cannibal',
    'a serial killer',
    'possessed by a daemon, on a mission from hell',
    'a daemon, looking to make a deal or sow strife',
    'cursed',
    'a cultist of the two-headed basalisk',
    'the leader of a cannibal cult',
    'a noble, running away from home',
    'just a figment of your fractured mind'
];

export const SPECIES = [
    'Earthbound',
    'Wild Wickhead',
    'Pale One',
    'Basalisk-born',
    'Gnoll',
    'Human',
    'Skeleton',
    'Giant',
    'Half-Giant',
    'Bisontaur',
    'Ghoul',
];

export const FUR = [
    'greasy black',
    'blood red',
    'gravedirt brown',
    'bile yellow',
    'bone white',
];

export const SCALES = [
    'void black',
    'blood red',
    'rust orange',
    'bile yellow',
    'bruise blue',
    'rotting green',
    'unfathomably violet'
];

export const MAIN_PRONOUN = [
    'He',
    'She',
    'They'
];

export const SECONDARY_PRONOUN = [
    'Him',
    'Her',
    'Them'
];

export const SKIN_TONE = [
    'ashen',
    'leathery tanned',
    'onxy',
    'ruddy',
    'clay',
    'driftwood'
];

export const BUILD = [
    'stout',
    'gaunt',
    'rotund',
    'muscular',
    'curvacious',
    'starved',
];

export const WHATTHEYVALUE = [
    'fireside chats',
    'praise and headpats',
    'endless work so they feel useful for once in their life',
    'material goods',
    'a warm, willing partner to lay with',
    'diluted poison, just enough to help forget the atrocities',
    'the chance to speak about themselves for hours and hours and hours',
    'screaming and yelling matches within the group, to remind them of home',
    'sharp weapons to add to their worrisome collection',
    'charred meat, doesn\'t matter where it came from',
    'depressing stories',
    'captured slaves',
    'a chance to rest and just watch sometimes',
    'soap, water, and a brush to clean themselves with',
    'gloomy music to fall asleep to',
    'complete darkness to submerge themselves into for a few hours',
    'fine wine. The older, the better',
    'dubious rituals that everyone takes part in',
    'payment in silver. No other metal will do',
    'food',
    'gossip',
    'whisky, grog, vodka, and beer',
    'pointless deaths. For others and eventually themself',
    'credit for all the work'
];

export const SPECIALITY = [
    'can disarm traps that you must first spot (DR8)',
    'can pilfer an item that fits in their pocket or fist (DR8)',
    'can scramble along impossible routes, such as sheer walls, without any special gear (DR8)',
    'can find spaces that the party can hide in (DR8)',
    'can create d2 doses of a random potion (pg. 56)',
    'can secrete d2 doses of a foul smelling healing potion (heals d6 HP and stops infection), once per day',
    'can use one random unclean spell, once per day',
    'can use one random sacred spell, once per day',
    'can glow with a strange bioluminescence, lighting the darkness',
    'can wield a knife like no other (d4+2)',
    'can backstab a target (DR8. Deals weapon damage +3)',
    'can cook an excellent meal (recover an extra d4 HP when resting)',
    'can help the party avoid getting lost',
    'can sense danger by scenting it on the wind',
    'can make and repair non-magickal items'
];